# This workflow file is currently disabled during development.
# It will be used for automated data collection when ready to deploy.
name: YC Data Collection

on:
  # Run weekly on Monday mornings
  schedule:
    - cron: "0 5 * * 1" # 5:00 AM UTC every Monday

  # Allow manual triggering from GitHub UI
  workflow_dispatch:

jobs:
  collect-data:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Check if update is needed
        id: check-update
        run: |
          python scripts/collect_data.py --check-only

      - name: Run YC data collection
        run: |
          python scripts/collect_data.py --source=yc

      - name: Commit changes
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add -A
          git diff --quiet && git diff --staged --quiet || (git commit -m "Update YC startup data - $(date +%Y-%m-%d)" && git push)
