# This workflow file is currently disabled during development.
# It will be used for API deployment when ready to deploy.
name: disabled-deploy-api

on:
  # This workflow will only run when manually triggered
  workflow_dispatch:

jobs:
  # Empty job that does nothing
  placeholder:
    runs-on: ubuntu-latest
    steps:
      - name: No-op
        run: echo "This workflow is currently disabled during development."
